---
# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    # Amazon S3 Storage Configuration
    s3_access_key: _env:AWS_ACCESS_KEY
    s3_secret_key: _env:AWS_SECRET_KEY
    boto_bucket: adc-docker-images
    s3_encrypt: true
    s3_secure: true
    secret_key: _env:DOCKER_REGISTRY_SECRET
    standalone: true

# This is the default configuration when no flavor is specified
dev:
    storage: s3
    storage_path: /dev
    loglevel: debug

# To specify another flavor, set the environment variable SETTINGS_FLAVOR
# $ export SETTINGS_FLAVOR=prod
prod:
    storage: s3
    storage_path: /prod
    # Enabling these options makes the Registry send an email on each code Exception
    # email_exceptions:
    #     smtp_host: REPLACEME
    #     smtp_login: REPLACEME
    #     smtp_password: REPLACEME
    #     from_addr: docker-registry@localdomain.local
    #     to_addr: noise+dockerregistry@localdomain.local

# This flavor is automatically used by unit tests
test:
    storage: local
    storage_path: /tmp/test
